name: Build & Deploy Container App POC

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create resource group
        run: az group create -n ${{ env.AZ_RG }} -l ${{ env.AZ_LOC }}

      - name: Deploy Container App job (script)
        run: |
          chmod +x ./azure/deploy_containerapp_job.sh
          ./azure/deploy_containerapp_job.sh ${{ env.AZ_RG }} ${{ env.AZ_CA_ENV }} ${{ env.AZ_JOB_NAME }} ${{ env.AZ_LOC }}
        env:
          AZ_RG: ${{ secrets.AZ_RG }}
          AZ_LOC: ${{ secrets.AZ_LOCATION }}
          AZ_CA_ENV: ${{ secrets.AZ_CA_ENV }}
          AZ_JOB_NAME: ${{ secrets.AZ_JOB_NAME }}
